spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_message_queue
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: localhost
    port: 5672
